server {
  listen 80;
  server_name v.joho.cn;
  # 微信服务器配置校验走 http get，301 到 https 以拿到 https URL 更稳；但先看现配置
  location / { proxy_pass http://127.0.0.1:1337; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
}