type Method = "GET" | "POST" | "PUT" | "DELETE" | "PATCH";

const channelScopeRoute = (
  method: Method,
  path: string,
  handler: string,
  permission: string,
) => ({
  method,
  path: `/v1/admin${path}`,
  handler,
  config: {
    auth: false,
    policies: [
      "plugin::zhao-auth.is-authenticated",
      { name: "plugin::zhao-auth.has-permission", config: { action: permission } },
      "plugin::zhao-auth.has-channel-scope",
      "plugin::zhao-auth.has-tenant-access",
    ],
  },
});

export default () => ({
  type: "content-api" as const,
  routes: [
    channelScopeRoute("GET", "/articles", "article-admin.find", "article.read"),
    channelScopeRoute("GET", "/articles/:documentId", "article-admin.findOne", "article.read"),
    channelScopeRoute("POST", "/articles", "article-admin.create", "article.create"),
    channelScopeRoute("PUT", "/articles/:documentId", "article-admin.update", "article.update"),
    channelScopeRoute("DELETE", "/articles/:documentId", "article-admin.delete", "article.update"),
    channelScopeRoute("POST", "/articles/:documentId/publish", "article-admin.publish", "article.publish"),
    channelScopeRoute("POST", "/articles/:documentId/archive", "article-admin.archive", "article.publish"),
    channelScopeRoute("POST", "/articles/batch", "article-admin.batch", "article.publish"),
    channelScopeRoute("GET", "/seo-config", "seo-config-admin.find", "seo-config.read"),
    channelScopeRoute("PUT", "/seo-config", "seo-config-admin.update", "seo-config.update"),
    channelScopeRoute("GET", "/brand-info", "brand-info-admin.find", "brand-info.read"),
    channelScopeRoute("PUT", "/brand-info", "brand-info-admin.update", "brand-info.update"),
    channelScopeRoute("GET", "/article-categories", "article-category-admin.find", "article-category.read"),
    channelScopeRoute("GET", "/article-categories/:documentId", "article-category-admin.findOne", "article-category.read"),
    channelScopeRoute("POST", "/article-categories", "article-category-admin.create", "article-category.create"),
    channelScopeRoute("PUT", "/article-categories/:documentId", "article-category-admin.update", "article-category.update"),
    channelScopeRoute("DELETE", "/article-categories/:documentId", "article-category-admin.delete", "article-category.delete"),
    channelScopeRoute("GET", "/products", "product-admin.find", "product.read"),
    channelScopeRoute("GET", "/products/:documentId", "product-admin.findOne", "product.read"),
    channelScopeRoute("POST", "/products", "product-admin.create", "product.create"),
    channelScopeRoute("PUT", "/products/:documentId", "product-admin.update", "product.update"),
    channelScopeRoute("DELETE", "/products/:documentId", "product-admin.delete", "product.delete"),
    channelScopeRoute("GET", "/cases", "case-admin.find", "case.read"),
    channelScopeRoute("GET", "/cases/:documentId", "case-admin.findOne", "case.read"),
    channelScopeRoute("POST", "/cases", "case-admin.create", "case.create"),
    channelScopeRoute("PUT", "/cases/:documentId", "case-admin.update", "case.update"),
    channelScopeRoute("DELETE", "/cases/:documentId", "case-admin.delete", "case.delete"),
    channelScopeRoute("GET", "/compliance", "compliance-admin.find", "compliance.read"),
    channelScopeRoute("GET", "/compliance/:documentId", "compliance-admin.findOne", "compliance.read"),
    channelScopeRoute("POST", "/compliance", "compliance-admin.create", "compliance.create"),
    channelScopeRoute("PUT", "/compliance/:documentId", "compliance-admin.update", "compliance.update"),
    channelScopeRoute("DELETE", "/compliance/:documentId", "compliance-admin.delete", "compliance.update"),
    channelScopeRoute("GET", "/faqs", "faq-admin.find", "faq.read"),
    channelScopeRoute("GET", "/faqs/:documentId", "faq-admin.findOne", "faq.read"),
    channelScopeRoute("POST", "/faqs", "faq-admin.create", "faq.create"),
    channelScopeRoute("PUT", "/faqs/:documentId", "faq-admin.update", "faq.update"),
    channelScopeRoute("DELETE", "/faqs/:documentId", "faq-admin.delete", "faq.delete"),
    channelScopeRoute("GET", "/tutorials", "tutorial-admin.find", "tutorial.read"),
    channelScopeRoute("GET", "/tutorials/:documentId", "tutorial-admin.findOne", "tutorial.read"),
    channelScopeRoute("POST", "/tutorials", "tutorial-admin.create", "tutorial.create"),
    channelScopeRoute("PUT", "/tutorials/:documentId", "tutorial-admin.update", "tutorial.update"),
    channelScopeRoute("DELETE", "/tutorials/:documentId", "tutorial-admin.delete", "tutorial.delete"),
    channelScopeRoute("GET", "/downloads", "download-admin.find", "download.read"),
    channelScopeRoute("GET", "/downloads/:documentId", "download-admin.findOne", "download.read"),
    channelScopeRoute("POST", "/downloads", "download-admin.create", "download.create"),
    channelScopeRoute("PUT", "/downloads/:documentId", "download-admin.update", "download.update"),
    channelScopeRoute("DELETE", "/downloads/:documentId", "download-admin.delete", "download.delete"),
    channelScopeRoute("GET", "/leads", "lead-admin.find", "lead.read"),
    channelScopeRoute("GET", "/leads/:documentId", "lead-admin.findOne", "lead.read"),
    channelScopeRoute("PUT", "/leads/:documentId", "lead-admin.update", "lead.update"),
    channelScopeRoute("DELETE", "/leads/:documentId", "lead-admin.delete", "lead.delete"),
    channelScopeRoute("GET", "/visit-logs", "visit-log-admin.find", "visit-log.read"),
    channelScopeRoute("GET", "/interactions", "interaction-admin.find", "interaction.read"),
    channelScopeRoute("GET", "/search-logs", "search-log-admin.find", "search-log.read"),
    channelScopeRoute("GET", "/kg/entities", "knowledge-graph.findEntities", "knowledge-entity.read"),
    channelScopeRoute("POST", "/kg/entities", "knowledge-graph.createEntity", "knowledge-entity.create"),
    channelScopeRoute("PUT", "/kg/entities/:documentId", "knowledge-graph.updateEntity", "knowledge-entity.update"),
    channelScopeRoute("DELETE", "/kg/entities/:documentId", "knowledge-graph.deleteEntity", "knowledge-entity.delete"),
    channelScopeRoute("GET", "/kg/relations", "knowledge-graph.findRelations", "knowledge-relation.read"),
    channelScopeRoute("POST", "/kg/relations", "knowledge-graph.addRelation", "knowledge-relation.create"),
    channelScopeRoute("DELETE", "/kg/relations/:documentId", "knowledge-graph.deleteRelation", "knowledge-relation.delete"),
    channelScopeRoute("POST", "/kg/disambiguate", "knowledge-graph.disambiguate", "knowledge-entity.read"),
    channelScopeRoute("GET", "/kg/export", "knowledge-graph.exportGraph", "knowledge-entity.read"),
    channelScopeRoute("GET", "/first-truths", "first-truth.find", "first-truth.read"),
    channelScopeRoute("GET", "/first-truths/:documentId", "first-truth.findOne", "first-truth.read"),
    channelScopeRoute("POST", "/first-truths", "first-truth.create", "first-truth.create"),
    channelScopeRoute("PUT", "/first-truths/:documentId", "first-truth.update", "first-truth.update"),
    channelScopeRoute("DELETE", "/first-truths/:documentId", "first-truth.delete", "first-truth.delete"),
    channelScopeRoute("POST", "/first-truths/:documentId/verify", "first-truth.verify", "first-truth.update"),
    channelScopeRoute("GET", "/first-truths/conflicts", "first-truth.conflicts", "first-truth.read"),
    channelScopeRoute("GET", "/first-truths/export", "first-truth.exportFacts", "first-truth.read"),
    channelScopeRoute("GET", "/ai-summaries", "ai-content-summary.findByTarget", "ai-summary.read"),
    channelScopeRoute("POST", "/ai-summaries", "ai-content-summary.create", "ai-summary.create"),
    channelScopeRoute("PUT", "/ai-summaries/:documentId", "ai-content-summary.update", "ai-summary.update"),
    channelScopeRoute("DELETE", "/ai-summaries/:documentId", "ai-content-summary.delete", "ai-summary.delete"),
    channelScopeRoute("POST", "/ai-summaries/:documentId/regenerate", "ai-content-summary.regenerate", "ai-summary.update"),
    channelScopeRoute("POST", "/studio-bridge/publish", "studio-bridge.publishFromStudio", "article.create"),
    channelScopeRoute("GET", "/stats/overview", "stats.overview", "article.read"),
    channelScopeRoute("GET", "/stats/leads", "stats.leadStats", "lead.read"),
    channelScopeRoute("GET", "/stats/search", "stats.searchStats", "search-log.read"),
  ],
});
